### ISSUE TITLE
Add listen ports to build

### ISSUE THREAD

**Issue by DocCyblade** [MPTMG/Mumble#2]
I assume Mumble uses incoming TCP/IP ports for incoming connections. I believe the you need to add them to [your make file here](https://github.com/MPTMG/Mumble/blob/master/Makefile#L1). That is a list of ports that the firewall will be open.

**Comment by MPTMG** [comment]
I will add the default where suggested however when running multiple instances you select the port when creating another mumble server. How would you handle that? Add a port range?

**Comment by DocCyblade** [comment]
Is there anyway the software has plug-ins or hooks you could use to write a script to add/remove ports

**Comment by MPTMG** [comment]
Running this one to ground to see if there are any plug-ins or hooks to get a script to monitor and open ports. In interim I will add the default port. Will come back to this.

**Comment by MPTMG** [comment]
Do ports that are listening on the loopback interface need to be added as well?

**Comment by DocCyblade** [comment]
AFAIK only ports that will be access outside the system. So if you app is using local port to talk to another app that should be ok.

**Comment by MPTMG** [comment]
Necessary ports were added.

**Comment by DocCyblade** [comment]
This looks good as well. Not sure how we can automate the firewall. When you create a channel does it give you a range of ports? You could open up the range

**Comment by MPTMG** [comment]
I am still working this my first thought is to open a range starting at the default port and then opening up a specific number of ports in sequential order ascending for additional servers. From what I have been able to ascertain from google.... a mumble server with 50 active users takes about 512mb of ram. Hence on one server/vm I don't see people running a ton of instances, but who knows. I would imagine having ten ports open would be overkill for most users. I originally took this on because the price people want for a hosted mumble app is more than the cost of a dedicated ec2 instance that could run multiple mumble servers.

I am currently working a script to handle opening ports. One of the other available interfaces (phpMumbleAdmin) automatically increments the port number as you add servers. I am seeing what they do to detect each server instance in order to script something to open ports. I may add the phpMumbleAdmin interface as well listening on another port just so people have options (I will create the branch soon). No gurantees on the script as there are significant unknowns still.

**Comment by MPTMG** [comment]
Are we talking a script just to modify IP table rules or something much more complicated?

**Comment by MPTMG** [comment]
I could see doing this with local firewall rules, but I am guessing you are talking about automating security policy/firewall of ec2 instances. If you are talking about automating the security on an ec2 instance I support opening a port range of 10-20 ports starting at 64738 and providing information about which ports to use in conf console and in the tk web control panel landing page. So the user can create murmur instances on the corrosponding ports. If the user is going beyond 10-20 instances of murmur I think it is safe to say they can handle opening a few ports through ec2.

**Comment by DocCyblade** [comment]
Local firewall yes. I am not sure how Turnkey Linux deployed on the hub works with firewall rules. @JedMeister could answer that.

**Comment by JedMeister** [comment]
TurnKey uses the ports in the makefile to configure IPTables. However IPTables is disabled by default (the user needs to enable it). 

When servers run on Amazon though, the ports from the makefile are reused for the auto configuration of the AWS security profile. I don't know enough about how that all works to give you any advice on it though sorry.

>  If you are talking about automating the security on an ec2 instance I support opening a port range of 10-20 ports starting at 64738 and providing information about which ports to use in conf console and in the tk web control panel landing page. So the user can create murmur instances on the corrosponding ports. If the user is going beyond 10-20 instances of murmur I think it is safe to say they can handle opening a few ports through ec2.

I agree, that sounds totally reasonable!

**Comment by MPTMG** [comment]
I have automatic port opening working for iptables firewall and I will commit it to the repo today (just need to make it a daemon to run at startup as opposed to everyboot folder. Essentially what I have done is "lsof | sed" to get what ports murmurd (mumble) is listening on. Then a "iptables -L | sed" to get firewall rules added for murmurd. It then compares the two outputs. If there is a murmurd listening without a rule it creates a rule. If there is a rule without an active murmurd listening it deletes the rule. It was actually stupid simple besides getting the sed commands just right. I will not be doing anything for automating ec2 as I don't even know if there is an API to work with. If someone has a link to the API where I could find the details I will put it on my bucket list.

**Comment by JedMeister** [comment]
Great work. That sounds like a pretty cool approach! :smile: 

There may be an API, but I have no expectation that you would include that sort of thing. Like I said, I think it's totally legitimate to provide an initial config with some reasonable defaults and documentation to add additional ports. So long as there is a note about it in the readme (which is converted into the appliance page) further documentation on that can wait (or we could possibly just point to an AWS doc page?).

**Comment by MPTMG** [comment]
I have iptables firewall rules automatically generated now based off a script run as a daemon at startup. It monitors listening ports filtered for the process murmurd and firewall rules filtered based off comment when rule is added. It is quick, dirty, and effective. I defaulted it to 5 minute refresh, so within 5 minutes of creating another murmurd instance the port will automatically be opened. It works for closing ports as well when an instance of murmurd is stopped.

I am not going to worry about the ec2 stuff for now beyond leaving the default listening port in the makefile.

The quick dirty firewall script already integrated in Mumble appliance....
https://github.com/MPTMG/murmurdautofirewall

**Comment by MPTMG** [comment]
Considering this resolved unless I hear otherwise. I will let you guys close this if you consider it complete as well.

**Comment by DocCyblade** [comment]
Since my issue was with the build scripts, and you went to the next level with making sure ports were open and closed with the firewall. Considered it complete for me
