### ISSUE TITLE
SSL Certs are baked in

### ISSUE THREAD

**Issue by DocCyblade** [MPTMG/Mumble#3]
You should be able to remove [the code you have regarding SSL certs](https://github.com/MPTMG/Mumble/blob/master/conf.d/main#L20) and use the ones that gets generated at first boot. You can find the [SSL harding script here.](https://github.com/turnkeylinux/common/blob/master/conf/turnkey.d/zz-ssl-ciphers#L9) It also shows the default location of the out of the box self signed certs They get [regenerated here during first boot init scripts from common](https://github.com/turnkeylinux/common/blob/b451a99b95f52f3c0021d8874b9faeccbeccbee3/overlays/turnkey.d/sslcert/usr/lib/inithooks/firstboot.d/15regen-sslcert).

**Comment by MPTMG** [comment]
Excellent I will remove the SSL generation in con.d/main

**Comment by MPTMG** [comment]
Deleted code regarding SSL certs and with integration of parts from common apache overlays SSL is done without any real effort on my part. Nice to see common can take care of so much detail if used properly. My compliments to the maintainers at TKL for providing such user friendly tools. Changes will be included in the next commit.

**Comment by MPTMG** [comment]
Default certs generated by turnkey common are now used.
