### ISSUE TITLE
Use common where you can

### ISSUE THREAD

**Issue by DocCyblade** [MPTMG/Mumble#4]
If you have not already, [take a look at the common folder.](https://github.com/turnkeylinux/common/tree/master) Use what you can from here. I always like to browse around to see what parts get added to the LAMP and LAPP builds, since a lot of the builds use LAMP or LAPP as a base to see whats getting called. There might already be something you need already here in common, in that case import it by putting it in your Makefile. [See the LAMP build code for an example](https://github.com/turnkeylinux-apps/lamp)

**Comment by MPTMG** [comment]
Thanks for the comment here I was not aware of the additions I could cherry pick from common and I am already integrating the relevant parts (apache, php, tkl-webcp). I should have figured this out as some of the artwork used in the LAMP application was not in its repo and I had to manually retrieve and incorporate.

**Comment by MPTMG** [comment]
Relevant parts from common are now integrated.

**Comment by DocCyblade** [comment]
This also looks good and can be closed
