### ISSUE TITLE
Use 'service" command as opposed to 'systemctl' in inithooks

### ISSUE THREAD

**Issue by JedMeister** [MPTMG/Mumble#6]
Due to a bug in the Debian Jessie SystemD implementation our container builds still use Sys V Init. So to ensure that appliance works for all users, please use `service NAME start|stop|restart` rather than `systemctl start|stop|restart NAME.service`.

I found a couple of entries but haven't search exhaustively yet. E.g.: https://github.com/MPTMG/Mumble/blob/master/overlay/usr/lib/inithooks/bin/icesecretset.sh#L18

PS FWIW it doesn't matter so much in the conf script, but to be consistent it's desirable.

**Comment by MPTMG** [comment]
Changes made and committed. Found two areas where I was using systemctl.
